blueprint:
  name: ZHC5010 Button Light Control
  description: Control different lights with each button on the ZHC5010 using Z-Wave JS.
  domain: automation
  input:
    zhc5010_device:
      name: ZHC5010 Device
      description: Select the ZHC5010 device to use.
      selector:
        device:
          integration: zwave_js
          manufacturer: Logic Group
          model: ZHC5010
    button_1_light:
      name: Button 1 Light
      description: Select the light to control with Button 1 (optional).
      selector:
        entity:
          domain: light
          multiple: false
    button_2_light:
      name: Button 2 Light
      description: Select the light to control with Button 2 (optional).
      selector:
        entity:
          domain: light
          multiple: false
    button_3_light:
      name: Button 3 Light
      description: Select the light to control with Button 3 (optional).
      selector:
        entity:
          domain: light
          multiple: false
    button_4_light:
      name: Button 4 Light
      description: Select the light to control with Button 4 (optional).
      selector:
        entity:
          domain: light
          multiple: false
    hold_brightness:
      name: Hold Brightness
      description: Brightness level to set when the button is held.
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
    transition_time:
      name: Transition Time
      description: Set the transition speed (in seconds) for light changes.
      default: 1.0
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "s"
          mode: slider
          step: 0.1

mode: single
max_exceeded: silent
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zhc5010_device

variables:
  button_id: '{{ trigger.event.data.property_key_name }}'
  button_action: '{{ trigger.event.data.value }}'
  hold_brightness: !input hold_brightness
  transition_time: !input transition_time
  button_1_light: !input button_1_light
  button_2_light: !input button_2_light
  button_3_light: !input button_3_light
  button_4_light: !input button_4_light

action:
  # Button 1 actions
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ button_id == '001' and button_1_light }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyPressed' }}"
              sequence:
                - choose:
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_1_light }}"
                          state: "on"
                      sequence:
                        - service: light.turn_off
                          data:
                            entity_id: "{{ button_1_light }}"
                            transition: "{{ transition_time }}"
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_1_light }}"
                          state: "off"
                      sequence:
                        - service: light.turn_on
                          data:
                            entity_id: "{{ button_1_light }}"
                            brightness_pct: 100
                            transition: "{{ transition_time }}"
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyHeldDown' }}"
              sequence:
                - service: light.turn_on
                  data:
                    entity_id: "{{ button_1_light }}"
                    brightness_pct: "{{ hold_brightness }}"
                    transition: "{{ transition_time }}"

  # Button 2 actions
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ button_id == '002' and button_2_light }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyPressed' }}"
              sequence:
                - choose:
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_2_light }}"
                          state: "on"
                      sequence:
                        - service: light.turn_off
                          data:
                            entity_id: "{{ button_2_light }}"
                            transition: "{{ transition_time }}"
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_2_light }}"
                          state: "off"
                      sequence:
                        - service: light.turn_on
                          data:
                            entity_id: "{{ button_2_light }}"
                            brightness_pct: 100
                            transition: "{{ transition_time }}"
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyHeldDown' }}"
              sequence:
                - service: light.turn_on
                  data:
                    entity_id: "{{ button_2_light }}"
                    brightness_pct: "{{ hold_brightness }}"
                    transition: "{{ transition_time }}"

  # Button 3 actions
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ button_id == '003' and button_3_light }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyPressed' }}"
              sequence:
                - choose:
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_3_light }}"
                          state: "on"
                      sequence:
                        - service: light.turn_off
                          data:
                            entity_id: "{{ button_3_light }}"
                            transition: "{{ transition_time }}"
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_3_light }}"
                          state: "off"
                      sequence:
                        - service: light.turn_on
                          data:
                            entity_id: "{{ button_3_light }}"
                            brightness_pct: 100
                            transition: "{{ transition_time }}"
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyHeldDown' }}"
              sequence:
                - service: light.turn_on
                  data:
                    entity_id: "{{ button_3_light }}"
                    brightness_pct: "{{ hold_brightness }}"
                    transition: "{{ transition_time }}"

  # Button 4 actions
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ button_id == '004' and button_4_light }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyPressed' }}"
              sequence:
                - choose:
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_4_light }}"
                          state: "on"
                      sequence:
                        - service: light.turn_off
                          data:
                            entity_id: "{{ button_4_light }}"
                            transition: "{{ transition_time }}"
                    - conditions:
                        - condition: state
                          entity_id: "{{ button_4_light }}"
                          state: "off"
                      sequence:
                        - service: light.turn_on
                          data:
                            entity_id: "{{ button_4_light }}"
                            brightness_pct: 100
                            transition: "{{ transition_time }}"
              - conditions:
                  - condition: template
                    value_template: "{{ button_action == 'KeyHeldDown' }}"
              sequence:
                - service: light.turn_on
                  data:
                    entity_id: "{{ button_4_light }}"
                    brightness_pct: "{{ hold_brightness }}"
                    transition: "{{ transition_time }}"
